USE Lab2;

ALTER TABLE Customer_T ADD CONSTRAINT Customer_PK PRIMARY KEY (CustomerID);
ALTER TABLE Order_T ADD CONSTRAINT Order_PK PRIMARY KEY (OrderID);
ALTER TABLE Order_T ADD CONSTRAINT Order_FK1 FOREIGN KEY (CustomerID) REFERENCES Customer_T(CustomerID);
ALTER TABLE Product_T ADD CONSTRAINT Product_PK PRIMARY KEY (ProductID);
ALTER TABLE OrderLine_T ADD CONSTRAINT OrderLine_PK PRIMARY KEY (OrderID, ProductID);
ALTER TABLE OrderLine_T ADD CONSTRAINT OrderLine_FK1 FOREIGN KEY (OrderID) REFERENCES Order_T(OrderID);
ALTER TABLE OrderLine_T ADD CONSTRAINT OrderLine_FK2 FOREIGN KEY (ProductID) REFERENCES Product_T(ProductID);


DESCRIBE Customer_T;
DESCRIBE Order_T;
DESCRIBE OrderLine_T;
DESCRIBE Product_T;